name = "Baysor"
uuid = "cc9f9468-1fbe-11e9-0acf-e9460511877c"
authors = ["Viktor Petukhov <viktor.petukhov+gh@pm.me>"]
version = "0.6.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastRandPCA = "cd768af4-c647-49d3-847e-9c96ab5a17a9"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
GeometricalPredicates = "fd0ad045-b25c-564e-8f9c-8ef5c5f21267"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LazyModules = "8cdb02fc-e678-4876-92c5-9defec4f444e"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UMAP = "c4f8c510-2410-5be4-91d7-4fbaeb39457e"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Vega = "239c3e63-733f-47ad-beb7-a12fde22c578"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
VoronoiDelaunay = "72f80fcb-8c52-57d9-aff0-40c1a3526986"

[compat]
CSV = "~0.10"
CairoMakie = "~0.10"
ColorSchemes = "~3.20"
Colors = "~0.12"
Comonicon = "~1.0"
Configurations = "~0.17"
DataFrames = "1.4, 1.5"
Distances = "~0.10"
Distributions = "~0.25"
FastRandPCA = "^0.2.1"
FileIO = "~1.16"
FiniteDiff = "~2.17"
GeometricalPredicates = "~0.4"
Graphs = "1.7, 1.8"
HDF5 = "~0.16"
ImageCore = "~0.9"
ImageIO = "~0.6"
ImageMorphology = "~0.3"
JSON = "~0.21"
LazyModules = "~0.3"
MAT = "~0.10"
Makie = "~0.19"
MultivariateStats = "~0.10"
NearestNeighbors = "~0.4"
ProgressMeter = "~1.7"
StaticArrays = "~1.5"
StatsBase = "~0.33"
UMAP = "^0.1.9"
Vega = "~2.3"
VegaLite = "~2.6"
VoronoiDelaunay = "~0.4"
julia = "^1.7"
